### ISSUE TITLE
Assertion failed during sanity check of build_causality_graph

### ISSUE THREAD

**Issue by tylergu** [sieve-project/sieve#19]
Backtrace:
```
Traceback (most recent call last):
  File "sieve.py", line 714, in <module>
    options.phase,
  File "sieve.py", line 498, in run
    phase,
  File "sieve.py", line 439, in run_test
    oracle_config,
  File "sieve.py", line 312, in check_result
    analyze.analyze_trace(project, log_dir, two_sided=two_sided)
  File "/home/tyler/sieve/analyze.py", line 372, in analyze_trace
    causality_graph = build_causality_graph(event_list, side_effect_list)
  File "/home/tyler/sieve/analyze.py", line 320, in build_causality_graph
    causality_graph.sanity_check()
  File "/home/tyler/sieve/analyze_util.py", line 508, in sanity_check
    > self.event_vertices[i - 1].content.id
AssertionError
```

## How to reproduce
Run learning stage for workload scaleup-scaledown-tserver in yugabyte-operator
`python3 sieve.py -p yugabyte-operator -d tylergu1998 -s learn -t scaleup-scaledown-tserver`

**Comment by tylergu** [comment]
Fixed by commit fc0d583a5ba03fdea18567021ae4f3d744d6493d
